# Generated by Django 3.2.21 on 2023-09-21 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='statements',
            table='statements',
        ),
    ]
