# Generated by Django 3.2.21 on 2023-09-21 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_alter_statements_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statements',
            new_name='Statement',
        ),
    ]
