# Generated by Django 3.2.21 on 2023-09-21 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_rename_statements_statement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statement',
            options={'verbose_name': 'Jarvis Dataset', 'verbose_name_plural': 'Jarvis Datasets'},
        ),
    ]
